GET http://localhost:3000/rental-offers

###

GET http://localhost:3000/rental-offers/649a157a948877d3dfb0bdd2

###

GET http://localhost:3000/rental-offers/{{$random.alphanumeric(24)}}

###

POST http://localhost:3000/rental-offers/
Content-Type: application/json

{
  "title": "{{$random.alphabetic(15)}}",
  "description": "{{$random.alphabetic(45)}}",
  "city": "{{$random.alphabetic(10)}}",
  "previewImage": "{{$exampleServer}}",
  "mainImages": ["{{$exampleServer}}", "{{$exampleServer}}"],
  "isPremium": true,
  "isFavorite": false,
  "rating": {{$random.float(5)}},
  "type": "{{$random.alphabetic(8)}}",
  "roomsCounter": {{$random.integer(10)}},
  "guestsCounter": {{$random.integer(10)}},
  "cost": {{$random.integer(10000)}},
  "amenities": ["{{$random.alphanumeric(10)}}", "{{$random.alphanumeric(10)}}", "{{$random.alphanumeric(10)}}"],
  "numberComments": {{$random.integer(1000)}},
  "coordinates": {
    "latitude": {{$random.float(5)}},
    "longitude": {{$random.float(5)}}
  }
}

###

PATCH http://localhost:3000/rental-offers/649a157a948877d3dfb0bd11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pY2hlbGxlQGdvb2dsZS5jb20iLCJpZCI6IjY0OTZmMDg2YWY1NWNjM2VmNjY4ZDVjMiIsImlhdCI6MTY4ODIxMjkwOSwiZXhwIjoxNjg4Mzg1NzA5fQ.gs9n4Pb0VLOrWV8UDffLdc9p3L8gCiHZBTUFrkjaCk4

{
  "cost": 666666
}

###

DELETE http://localhost:3000/rental-offers/648f6751572d72678f99d384
